---
title: "Assignment 6 SQL"
author: "Sam Feinberg"
format: html
editor: visual
---

```{r}
#| label: Set-up

setwd("C:/Users/samgf/Desktop/assignment-6-samfeinberg")
getwd()

library(tidyverse)
library(DBI)
library(dbplyr)
library(duckdb)
library(nycflights13)

```

### **Part I**

### a.

```{r}
#| label: Part 1a

conn <- dbConnect(duckdb(), "../assignment-6-samfeinberg/data/flights.duckdb", read_only = TRUE)

dbIsValid(conn)
dbListTables(conn)
dbListFields(conn, "flights")

dbGetQuery(conn, "SELECT *
            FROM flights
            LIMIT 10;")

# Here, I first connected with the database on duckdb using dbConnect(). I then checked the connection, and ran some tests to see the data. Then, I used dbGetQuery, and wrote an SQL query to see the first 10 rows from the flights table.
```

### b.

```{r}
#| label: Part 1b

# i.

dbGetQuery(conn, "SELECT COUNT(*) AS total_flights
            FROM flights")

# ii.

dbGetQuery(conn, "SELECT carrier, COUNT(*) AS total_flights_by_carrier
            FROM flights
            GROUP BY carrier")

# In this part, I first did a query to select the total amount of flights, by counting the total rows in the flights table. Then, I made a query to count the total flights for each carrier, by using GROUP BY to seperate the table by the carrier.

```

### c.

```{r}
#| label: Part 1c

dbGetQuery(conn, "SELECT AVG (dep_delay) AS avg_dep_delay,
            FROM flights")

# Here, I made a query to take the average of dep_delay and return that value.

```

### d. 

```{r}
#| label: Part 1d

dbGetQuery(conn, "SELECT dest, COUNT(*) AS total_flights,
           FROM flights
           GROUP BY dest
           ORDER BY total_flights DESC
           LIMIT 5")

# In this part, my query selected destination and a new variable called total flights. I used GROUP BY to count total flights at each destination, and ORDER BY to sort the flights at each destination in descending order. I lastly used LIMIT to only see the top 5 destinations for total flights.

```
